### ISSUE TITLE
RuntimeError: invalid indicator (URL)

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/py-csirtgsdk#58]
When submitting a some spam URLs using the SDK I got the following error:

```
2016-01-11 15:42:39,598 - ERROR - whitefacesdk.client[100] - request failed: 422
Traceback (most recent call last):
  File "wf-email-urls.py", line 99, in <module>
    main()
  File "wf-email-urls.py", line 94, in main
    'comment': comment
  File "wf-email-addresses/venv/local/lib/python2.7/site-packages/whitefacesdk/indicator.py", line 129, in submit
    return self.client.post(uri, data)
  File "wf-email-addresses/venv/local/lib/python2.7/site-packages/whitefacesdk/client.py", line 112, in post
    raise RuntimeError(err)
RuntimeError: invalid indicator: http://www.geldfa.de/3957/generic-ranitidine-online-pharmacy-canadian-zantac-compresse"]Low
```

Couple of thoughts:

1. Maybe the url ```http://www.geldfa.de/3957/generic-ranitidine-online-pharmacy-canadian-zantac-compresse"]Low``` shouldn't be a invalid indicator as you are able to browse to the URL via Google Chrome. 

2. If/when the SDK does come across a invalid indicator, should it raise a "RuntimeError" and halt all processing. In this instance, there were an array of indicators and it stopped processing in the middle of the array due to the run time error. Would it be better to just log the 'invalid indicator' and continuing processing the array of indicators?

**Comment by giovino** [comment]
Q2 is addressed (solved) in issue #67

**Comment by wesyoung** [comment]
are you sure the url was "...compresse"]Low" or was that a parsing flub?

ie: was the url supposed to be this:

http://www.geldfa.de/3957/generic-ranitidine-online-pharmacy-canadian-zantac-compresse

or this:

http://www.geldfa.de/3957/generic-ranitidine-online-pharmacy-canadian-zantac-compresse"]Low

**Comment by giovino** [comment]
yes it was and the double quotation is invalid
